// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw5ef.Models;

#nullable disable

namespace cw5ef.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("cw5ef.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrand = "Opel",
                            CarModel = "Astra",
                            Price = 50000m,
                            ProductionDate = new DateOnly(2010, 10, 10)
                        },
                        new
                        {
                            Id = 2,
                            CarBrand = "Opel",
                            CarModel = "Corsa",
                            Price = 30000m,
                            ProductionDate = new DateOnly(2015, 10, 10)
                        },
                        new
                        {
                            Id = 3,
                            CarBrand = "Volkswagen",
                            CarModel = "Golf",
                            Price = 60000m,
                            ProductionDate = new DateOnly(2018, 10, 10)
                        },
                        new
                        {
                            Id = 4,
                            CarBrand = "Volkswagen",
                            CarModel = "Passat",
                            Price = 80000m,
                            ProductionDate = new DateOnly(2019, 10, 10)
                        },
                        new
                        {
                            Id = 5,
                            CarBrand = "Audi",
                            CarModel = "A4",
                            Price = 120000m,
                            ProductionDate = new DateOnly(2020, 10, 10)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
