// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_ef.Models;

#nullable disable

namespace mvc_ef.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("mvc_ef.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Platformer",
                            Price = 39.99m,
                            ReDate = new DateOnly(1985, 9, 13),
                            Title = "Super Mario Bros"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action-Adventure",
                            Price = 49.99m,
                            ReDate = new DateOnly(1986, 2, 21),
                            Title = "The Legend of Zelda"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action-Adventure",
                            Price = 39.99m,
                            ReDate = new DateOnly(1986, 8, 6),
                            Title = "Metroid"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Role-Playing",
                            Price = 59.99m,
                            ReDate = new DateOnly(1987, 12, 18),
                            Title = "Final Fantasy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
