// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vs2022_ex_sqlite.Models;

#nullable disable

namespace vs2022_ex_sqlite.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("vs2022_ex_sqlite.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Porodukt 1",
                            Price = 23.89m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Porodukt 2",
                            Price = 23.89m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Porodukt 3",
                            Price = 23.89m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Porodukt 4",
                            Price = 23.89m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
