// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw5_ef.Models;

#nullable disable

namespace cw5_ef.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    partial class PersonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("cw5_ef.Models.MyPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("WorkPlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkPlaceId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 1, 1),
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            WorkPlaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1995, 2, 2),
                            FirstName = "Anna",
                            LastName = "Nowak",
                            WorkPlaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 3, 3),
                            FirstName = "Andrzej",
                            LastName = "Nowak",
                            WorkPlaceId = 2
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2005, 4, 4),
                            FirstName = "Krzysztof",
                            LastName = "Kowalski",
                            WorkPlaceId = 3
                        });
                });

            modelBuilder.Entity("cw5_ef.Models.WorkPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkerPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Klonowa 1",
                            Description = "Firma zajmująca się produkcją mebli"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Dębowa 2",
                            Description = "Firma zajmująca się produkcją okien"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ul. Sosnowa 3",
                            Description = "Firma zajmująca się produkcją drzwi"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ul. Brzozowa 4",
                            Description = "Firma zajmująca się produkcją podłóg"
                        });
                });

            modelBuilder.Entity("cw5_ef.Models.MyPerson", b =>
                {
                    b.HasOne("cw5_ef.Models.WorkPlace", "Place")
                        .WithMany("Workers")
                        .HasForeignKey("WorkPlaceId");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("cw5_ef.Models.WorkPlace", b =>
                {
                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
