// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw4ef.Models;

#nullable disable

namespace cw4ef.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20241118162515_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("cw4ef.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 200m,
                            ReleaseDate = new DateOnly(2020, 12, 10),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 2,
                            Price = 100m,
                            ReleaseDate = new DateOnly(2015, 5, 19),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Price = 50m,
                            ReleaseDate = new DateOnly(2011, 11, 11),
                            Title = "The Elder Scrolls V: Skyrim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
